### ISSUE TITLE
Error processing input

### ISSUE THREAD

**Issue by compellon** [uniVocity/univocity-parsers#11]
I have a csv file with a data such as this:

H23135.502,H17108.503,X55362.504,R53941.505,R98189.506,R53936.507,H01677.508,Z49199.509,D90188.510,H09599.511,H82631.512,M22382.513,T47562.514,T56604.515,M59807.516,U30827.517,M23410.518,M60484.519,T95048.520,H07899.521,T88902.522,M96839.523,H11650.524,U20659.525,M95678.526,U31215.527,R20804.528

The parser gives me a " processing input error " 
Error,com.univocity.parsers.common.TextParsingException: Error processing input: , line=0, char=5542. Content parsed: [null]
com.univocity.parsers.common.AbstractParser.handleException(AbstractParser.java:260)
com.univocity.parsers.common.AbstractParser.parse(AbstractParser.java:127)

It appears that the parseRecord() generates a java ArrayIndexOutOfBoundsException: 512 in the AbstractParser.java

I use a FileInputStream for my reader (in scala)
private def getReader(relativePath: String): java.io.Reader = {
    try {
      new InputStreamReader(new FileInputStream(relativePath))
    } catch {
      case e: Exception => {
        throw new EngineException("Unable to read input", true)
      }
    }
  }
Please let me know if you would need the csv file for debugging. Thanks!

**Comment by jbax** [comment]
By the looks of it:
1 - the file has more than 512 columns; or
2 - it does not have line separators

If that's the case, set the maximum number of columns in the [parser setttings](http://docs.univocity.com/parsers/1.3.0/com/univocity/parsers/common/CommonSettings.html#setMaxColumns(int)).

If the error persists, please send me the file to fix the error for you.

**Comment by jbax** [comment]
Assuming the problem is the wrong line separator. If you can't determine what it is beforehand, use the added [lineSeparatorDetection](http://docs.univocity.com/parsers/1.4.0/com/univocity/parsers/common/CommonParserSettings.html#setLineSeparatorDetectionEnabled(boolean)) introduced in version 1.4.0

Direct download link (if you can't get the artifact via maven yet - it's been just released)
http://oss.sonatype.org/content/repositories/releases/com/univocity/univocity-parsers/1.4.0/univocity-parsers-1.4.0.jar
