### ISSUE TITLE
will univocity-parsers support non-printable characters parse

### ISSUE THREAD

**Issue by ZzzCrazyPig** [uniVocity/univocity-parsers#115]
@jbax  I asked a question on stackoverflow before and got your answer. Is it better to make univocity-parsers **support non-printable characters parse** instead of using `settings.trimValues(false)` ? 

stackoverflow link :
[how-to-use-univocity-parsers-to-process-non-printable-character](http://stackoverflow.com/questions/39318083/how-to-use-univocity-parsers-to-process-non-printable-character/39323748#39323748)

**Comment by jbax** [comment]
Not sure if I follow. Do you want it to have different defaults, or is
there something you can't parse regardless of what settings you use?

On 5 Sep 2016 3:54 PM, "CrazyPig" <notifications@github.com> wrote:

@jbax <https://github.com/jbax> I asked a question on stackoverflow before
and got your answer. Is it better to make univocity-parsers *support
non-printable characters parse* instead of using settings.trimValues(false)
?

stackoverflow link :
how-to-use-univocity-parsers-to-process-non-printable-character
<http://stackoverflow.com/questions/39318083/how-to-use-univocity-parsers-to-process-non-printable-character/39323748#39323748>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/uniVocity/univocity-parsers/issues/115>, or mute the
thread

**Comment by ZzzCrazyPig** [comment]
I don't want non-printable character to be ignored as whitespace and furthermore to trim whitespace character before column values and after column value.

**Comment by jbax** [comment]
Well, any character `<= ' '` is generally considered a whitespace (see Java's own implementation of `String.trim()`)

You'd need to have a way to configure the parser with a list of characters that cannot be skipped as whitespace. That doesn't seem too hard to add to the library. 

I'm just wondering if calling "String.trim()" on columns where whitespace can be around values makes more sense as one might want to skip `\u0000` (i.e. `\0`) in some columns, but keep it in others - there's no sane configuration to handle this.

**Comment by jbax** [comment]
Added a configuration to make the parser/writer process bit values instead of considering them as whitespace. Use `setSkipBitsAsWhitespace(false)` in the configuration of either the parser or the writer to prevent characters `\0` and `\1` to be discarded as whitespace. 

A new 2.3.0-SNAPSHOT build has been released to include this feature.
