### ISSUE TITLE
Question on using univocity parsers within spark

### ISSUE THREAD

**Issue by compellon** [uniVocity/univocity-parsers#12]
Hi,
This is just a quick question for spark RDDs? Currently we are able to process a csv file with opencsv  in the following manner. Can we do the same thing with CsvParser / TsvParser?
   
 var rdd: RDD[String] = sparkcontext.textFile(filepath)
 .........
 .........
 rdd.mapPartitions(lines => {
        val parser = new CSVParser(rowSeparator)
        lines.map(line => {
          val row = parser.parseLine(line).map(o => Option(o).map(_.trim).getOrElse("")
          ...........
          row
        })
      })

**Comment by jbax** [comment]
Currently, uniVocity-parsers does not provide a `parseLine(String)` method or equivalent for this case where you are splitting the lines by yourself instead of using the parser. Careful when doing this because multi-line values can be a problem for you.

Considering each line contains proper CSV, you'd have to use something like the following (using Java code):

```
                //first create a row processor and a parser instance
                CsvParserSettings settings  = new CsvParserSettings();
		settings.setLineSeparatorDetectionEnabled(true);
		
		settings.setRowProcessor(new AbstractRowProcessor(){
			@Override
			public void rowProcessed(String[] row, ParsingContext context) {
				//process your row here
			}
		});
		
		CsvParser parser = new CsvParser(settings);
    
                // then process each line you got from the sparkContext:
		for(String line : lines){
			parser.parse(new StringReader(line));
		}
```

But I don't think this is optimal for your case in particular. We will introduce a `parseLine` equivalent on uniVocity-parsers 1.5.0.

If you are in a hurry and need this or other features immediately, we offer [paid support options](http://www.univocity.com/products/parsers-support) and allocate a developer to deliver this for you in less than 24 hours.

**Comment by compellon** [comment]
Thanks!. Please let us know when uniVocity-parsers 1.5.0. is pushed to git.
 For now you may close the ticket.

**Comment by jbax** [comment]
Keeping it open until 1.5.0 is released to address this particular case.

**Comment by jbax** [comment]
Method parseLine added in the following commit:
https://github.com/uniVocity/univocity-parsers/commit/4f145a4af171871e678b5161df0376822601ec88

Preparing to release version 1.5.0

**Comment by jbax** [comment]
Version 1.5.0 has been just released. It may take a few hours until the artifact is available on maven central repository, but you can download the latest release from the following link


http://oss.sonatype.org/content/repositories/releases/com/univocity/univocity-parsers/1.5.0/univocity-parsers-1.5.0.jar

**Comment by rajatm91** [comment]
We are trying to read a 3 gb file which has multiple new line character in one its column using spark-csv and univocity 1.5.0 parser, but  the file is getting splited in the multiple column in some row on the basis of newline character. This scenario is occurring in case of large file. So just wanted to know whether univocity parser parses the data on the basis of logical partition or physical partition.

**Comment by jbax** [comment]
Not really sure what spark-csv does exactly. It might be reading the rows
and sending each one to the parser, which would cause that problem. I also
have no clue what logical or physical partition means in this context.

Are you able to use the parser directly? 3gb is not too big.

Anyways, better to ask for help to the maintainers of spark-csv as I know
very little about how univocity-parsers is used by it.



On 17 Dec 2016 1:33 AM, "rajatm91" <notifications@github.com> wrote:

We are trying to read a 3 gb file which has multiple new line character in
one its column using spark-csv and univocity 1.5.0 parser, but the file is
getting splited in the multiple column in some row on the basis of newline
character. This scenario is occurring in case of large file. So just wanted
to know whether univocity parser parses the data on the basis of logical
partition or physical partition.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/uniVocity/univocity-parsers/issues/12#issuecomment-267612954>,
or mute the thread
