### ISSUE TITLE
how to work with hibernate validation?

### ISSUE THREAD

**Issue by duxy2002** [uniVocity/univocity-parsers#126]

**Comment by jbax** [comment]
Maybe by asking the Hibernate guys and providing a meaningful description of the problem you're having?

**Comment by duxy2002** [comment]
My Point is there are a lot of conversion functions in the  univocity-parsers, But why there is no validation function?

**Comment by jbax** [comment]
Because no one seemed to need this so far, as rows or beans can be easily
skipped. Feel free to submit a PR with your proposed improvement. Thanks!

On 24 Nov 2016 9:48 PM, "duxy2002" <notifications@github.com> wrote:

My Point is there are a lot of conversion functions in the
univocity-parsers, But why there is no validation function?

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/uniVocity/univocity-parsers/issues/126#issuecomment-262753017>,
or mute the thread
