### ISSUE TITLE
If number of columns of one row bigger than maxcolumns it stop parsing.

### ISSUE THREAD

**Issue by giaosudau** [uniVocity/univocity-parsers#164]
My data has some invalid lines contains more than maxColumns. 
And the parsing process stop there.
How to skip that line and continue to the next line?

**Comment by jbax** [comment]
You need to increase your `maxColumns` to be larger than what you are dealing with (if unsure use a big number).

We won't make the parser skip the line as you NEED to know of a potential problem and handle it accordingly.

**Comment by giaosudau** [comment]
@jbax This solution is not the one I'm looking for because even you increase the maxColumns it still have some lines have number of columns bigger than you number you set.
`We won't make the parser skip the line as you NEED to know of a potential problem and handle it accordingly.
`
This sound good but in some case we just want to parse the valid lines and print out the invalid one.

**Comment by jbax** [comment]
Sounds very dodgy. What makes a line invalid? How many columns can a row have in the worst case? 

Apparently you are getting errors because the format is not configured correctly and the parser can't find the end of a record, so it is adding columns to the same row over and over, until the end of the input. That is exactly why the `maxColumns` setting exists: it prevents you from getting an `OutOfMemoryError` and allows you to find issues in your configuration.

If unsure, set `maxColumns` to `1000000` or even `Integer.MAX_VALUE` (in this case just make sure to have enough memory allocated).

**Comment by giaosudau** [comment]
@jbax 
even I set 1000000 it still have maxColumns problem.
and it will cost lots of memory too.
So the solution to increase maxColumns doesn't work in my case.

**Comment by jbax** [comment]
Of course it's not a solution! The format is not configured to correctly to
parse the input you got.

Configure the format correctly FIRST.


On 8 Jun. 2017 10:58 am, "Chanh Le" <notifications@github.com> wrote:

@jbax <https://github.com/jbax>
even I set 1000000 it still have maxColumns problem.
and it will cost lots of memory too.
So the solution to increase maxColumns doesn't work in my case.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/uniVocity/univocity-parsers/issues/164#issuecomment-306971763>,
or mute the thread

**Comment by giaosudau** [comment]
So why don't we have a option to skip the invalid line like this?

**Comment by jbax** [comment]
Because it is not a line. It is the entire input stuffed in a single row
because the parser can not find the end of the record.

**Comment by giaosudau** [comment]
ok. I gave up on your lib.
