### ISSUE TITLE
Default implementation for non-primitive fields

### ISSUE THREAD

**Issue by PopescuStefanRadu** [uniVocity/univocity-parsers#171]
Right now, transforming an object into a CSV (or more) is a bit more work than just annotating the fields when the fields are not of primitive types(barring String of course). The common implementation in a RDBMS table structure would be pretty nice to have. If anyone needs anything more complicated they could just adapt your example.

Would you consider adding this?

**Comment by jbax** [comment]
Sorry but I'm not clear on what you are suggesting. Do you mind providing some examples with a sample input, sample code and expected output to clarify?

**Comment by PopescuStefanRadu** [comment]
Something along the lines of 
```
public class Order{
    @ForeignKey(class = Party.class, useRuntimeNameResolver = false, nameResolver="ClassSimpleNameResolver.class")
    @Parsed
    public Party orderParty;
    @ForeignKey(class = Party.class, useRuntimeNameResolver = false, nameResolver="ClassSimpleNameResolver.class")
    @Parsed
    public Party shipToParty;
    @ForeignKey(class = Party.class, useRuntimeNameResolver = false, nameResolver="ClassSimpleNameResolver.class")
    @Parsed
    public Party sellerParty;
}
```
```
public class Party{
    @ID
    @Parsed
    public long id;

    @Parsed
    public String name;
// etc. more fields 
// equals implementation that ignores id field
}
```

writing the Order class into a csv should output 2 .csv files:

order:
```
orderParty,shipToParty,sellerParty 
0,0,1
```

and
party.csv:
```
id,name
0,companyName0
1,companyName1
```
Party would of course need a proper .equals override that doesn't include the id.

I ended doing a conversion that does this, but it is not generic, nor based on annotations and the .csv file name of party.csv is decided at runtime, passed into the conversion constructor.

**Comment by jbax** [comment]
Sorry but this is way beyond the scope of the library. You're looking for an ORM. 

For this to have a chance to work we'd have to store a lot of stuff in memory because plain text files are not databases and don't support indexing or anything of the type, not to mention a lot of other corner cases.

For a simple case, you could try to define [your custom conversion](https://github.com/uniVocity/univocity-parsers#using-your-own-conversions-in-annotations) to write the `id` of your `Party` class, and make sure you don't create duplicate rows for each entry in `party.csv`.

Thanks for the suggestion.
