### ISSUE TITLE
CsvParserSettings.setDelimiterDetectionEnabled() not working anymore in version 2.5.2

### ISSUE THREAD

**Issue by duccom** [uniVocity/univocity-parsers#178]
CsvParserSettings.setDelimiterDetectionEnabled() not working in version 2.5.2, it's always return char comma (,) even the delimiter is semi colon (;) or pipe (|). When i changed back to version 2.1.1 everything fine. Please check.

**Comment by jbax** [comment]
Can you please provide a test case that reproduces the issue? I'll need the input file you are using to test this, or some sample that I can use to verify it.

Thank you!

**Comment by duccom** [comment]
i was testing very normal case:
file1.csv
---------------
a,b,c,
d,e,f
____________________
file2.csv
---------------
a|b|c
d|e|f
_____________________
java code:
`       List<String[]> allRows = new ArrayList<>();

        CsvParserSettings settings = new CsvParserSettings();
        
        settings.setDelimiterDetectionEnabled(true);
        settings.setQuoteDetectionEnabled(true);

        CsvParser parser = new CsvParser(settings);
        // print format before parse
        System.out.println(settings.getFormat());
        try {
            allRows = parser.parseAll(new FileInputStream("D:/file2.csv"));
            //print format after parse
            System.out.println(parser.getDetectedFormat());
        } catch (Exception e) {
            System.out.println(e);
        }`
Result
If i using file1.csv (delimiter comma), everthing file
If i using file2.csv (delimiter pipe), the output is wrong, and CSVFormat still showing delimiter=, (comma).
THe old version 2.1.1 does not have this problem

**Comment by jbax** [comment]
Fixed and released a 2.5.3-SNAPSHOT build which you can use to test.

A workaround is to provide the file encoding explicitly i.e. `parser.parseAll(new FileInputStream("D:/file2.csv", "UTF-8"));` so the parser won't have to try to identify a BOM marker on the input.

Thank you for using our parsers!

**Comment by brandonroubi** [comment]
Hi,
hope you are doing well. In order to parse csv with semi-colon, I download, compile and use 2.5.3-SNAPSHOT, but issue still remain.
below my csv 
`Matricule;Nom;Prenoms;Classe;Date de naissance;Date d'inscription;Tel
A12075;Mako;yao;6eme1;01/02/2007;15/10/2015;07108954
A12076;Mako;yao;6eme1;01/02/2007;15/10/2015;07108954
A12087;Mako;yao;6eme1;01/02/2007;15/10/2015;07108954`

My code
`CsvParserSettings parserSettings = new CsvParserSettings();
parserSettings.setLineSeparatorDetectionEnabled(true);
parserSettings.setDelimiterDetectionEnabled(true);
parserSettings.setQuoteDetectionEnabled(true);
RowListProcessor rowProcessor = new RowListProcessor();
parserSettings.setProcessor(rowProcessor);
parserSettings.setHeaderExtractionEnabled(true);
CsvParser parser = new CsvParser(parserSettings);
parser.parseAll(new InputStreamReader(uploadedFile.getInputstream(), "UTF-8"));
List<String[]> lignerslt = rowProcessor.getRows();`

Instead of 7 columns, I got 1 column with row as value. 

Could you kindly help me please.

**Comment by jbax** [comment]
Thank you @brandonroubi , it looks like the detection is thrown off by the `'` character in `Date d'inscription`. I'll make it work.

**Comment by jbax** [comment]
@brandonroubi  Fixed and released another 2.5.3-SNAPSHOT build. Thank you for reporting the error and for using our parsers!

**Comment by brandonroubi** [comment]
Noooooo, thanks to you for you amazing library. It works well !
