### ISSUE TITLE
Error mapping csv field to enum

### ISSUE THREAD

**Issue by nopantsmonkey** [uniVocity/univocity-parsers#199]
I am trying to map a csv field to enum using a simple converter and i am getting error "java.lang.ClassCastException: com.test.csvparse.Common$Access cannot be cast to java.lang.String"

myConverter -> [input => String || output => Access enum]

on debug i found out that
on that specific column of csv there were 2 converters 
1- MyConverter
2- EnumConverter

MyConverter.execute output is being send as input to EnumConverter.execute which is calling MyConverter.execute again so the problem here is EnumConverter.execute input is Access which is wrong as the implemented method requires a string therefore it crashes the program 

any way to fix this?

Mapping CSV field to this line below

```
@Parsed(field = "access")
@Convert(conversionClass = AccessConversion.class)
Access access;
```
Enum
```
public enum Access {FULL, NONE}
```

MyConverter
```
public class AccessConversion implements Conversion<String, Access> {
    public AccessConversion (String... args) {
    }

    @Override
    public Access execute(String s) {
        return setAccess(s);
    }

    @Override
    public String revert(Access o) {
        return revertAccess(o);
    }
}
```

**Comment by jbax** [comment]
The parser already converts to your enum. If you have an input such as:

```
access
FULL
NONE
```

You will only need the `@Parsed(field = "access")` annotation without a custom conversion class. You are getting the exception because the parser converted the string to an enum value, and tried to pass it to your custom conversion (i.e. your `execute(String s)` method) - which does not accept an enum type.

If you need to execute your custom conversion and make the parser send the input string to your custom conversion, then just add `applyDefaultConversion = false` to your `@Parsed` annotation:

```
        	@Parsed(field = "access", applyDefaultConversion = false)
		@Convert(conversionClass = AccessConversion.class)
		Access access;
```
