### ISSUE TITLE
Newlines in TSV values

### ISSUE THREAD

**Issue by ksmith97** [uniVocity/univocity-parsers#208]
It does not look like the Tsv parser supports quoted values, notably for the use case where values contain newlines? I am replacing an existing regex based parser suite in a legacy application and I was surprised by this.

This seems at least worth noting in the docs as it makes the tsv parser not fully compatible with excel exported files.  if you export a TSV file from excel with a newline it will produce a quote surrounded value and I think its safe to say that many of us are trying to support excel exported docs.

**Comment by jbax** [comment]
What you are parsing is a CSV that happens to use the tab character as the delimiter.

The TSV format does not have any special care for quotes, and new lines are escaped as `\` followed `n` or `r`. Alternatively, new lines can also be escaped as `\` followed by `\n`.

In you case just use the CsvParser class instead of the TsvParser to parse the input you got and you'll be fine.

**Comment by ksmith97** [comment]
You should document this! I know it seems obvious to you but until you suggested swapping delimiters I would not have thought of that.
