### ISSUE TITLE
Support CSV delimiters of more than one character

### ISSUE THREAD

**Issue by adutra** [uniVocity/univocity-parsers#209]
Delimiters of more than one character are fairly common, cf [this dataset](http://www.grouplens.org/system/files/ml-1m.zip).

Currently, such CSV files cannot be parsed with Univocity. 

Please provide support for this. Thanks in advance!

**Comment by jbax** [comment]
Thanks for the suggestion but it's not going to be implemented; at least not as part of the standard CSV parser. Inputs with delimiters such as the example you provided are generated using an arbitrary format that most of the time must be processed by a custom-built parser. In your example `::` is a field delimiter and `|`  a delimiter for values in a list. I can see that `::` was used as the delimiter because the `:` alone could easily appear as part of a field value and mess up the result without proper escaping. It's just easier for whoever produce this dataset to just avoid having to escape delimiters altogether. 

Maybe we could implement a `DelimitedTextParser` or something of the kind to assist processing these non-standard, ad-hoc formats.

I'll look at this again for version 3.0.0 and see if we can come with a useful parser for this sort of input.

Thanks!

**Comment by firefoxer1992** [comment]
Oh my god.. 
The method   setDelimiter() just support char .
`    public void setDelimiter(char delimiter) {
        this.delimiter = delimiter;
    }`
But I must set Delimiter  like "#|#"..
How could I  parse data  "RequestFailNumber#|#RequestNumber#|#StartTime#|#EndTime#|#InterfaceCode#|#WriteTime#|#RequestNumber#|#MondId" ?

**Comment by jbax** [comment]
Hello again. I've implemented support for delimiters of more than one character and it's available for testing on the latest 2.8.0-SNAPSHOT build. Let me know if you find any issues.

Instructions to get SNAPSHOT builds can be found here:
https://www.univocity.com/pages/univocity_parsers_download#snapshot-releases

Thank you for using our parsers!

**Comment by jbax** [comment]
Version 2.8.0 released. Thank you!

**Comment by fluxquantum** [comment]
Hi jbax, thank you for supporting this great tool. I was wondering if you could give me an example of how to use the multi-delimiter feature. I see its implementation on the parsing methods and the csv format class, but I was having a little trouble trying to enable it from CsvParserSettings setting the delimitersForDetection. Thanks for your time.

**Comment by jbax** [comment]
What do you mean by "multi-delimiter"? A delimiter with more than one
character? If that's the case there is no support to detect the format when
delimiters have more than one character. Also the parser does not support
multiple delimiters at once.

**Comment by fluxquantum** [comment]
Good morning jbax, thank you. Sorry, I misunderstood this issue. Looks like you added support for parsing using a delimiter of more than one character. But that doesn't extend to auto format detection and handling of files that have data using 2+different delimiters?

**Comment by jbax** [comment]
Precisely.
