### ISSUE TITLE
Usage of the @Format annotation

### ISSUE THREAD

**Issue by tonycatapano** [uniVocity/univocity-parsers#220]
I am trying to use the @Format annotation on my Pojo to get a number (represent with a String) filled with 0 when the parsed field has less than 8 digits like so:

```
@Format(formats = "00000000", options = "minimumIntegerDigits=8")     
@Parsed(field = "myfield")  
String myfield;
```

But it's not working. Tried also:

```
@Format(formats = "00000000") //NOT WORKING  
@Parsed(field = "myfield")  
String myfield;
```

and

```
@Format(formats = "########") //NOT WORKING  
@Parsed(field = "myfield")  
String myfield;
```

I see as many zeros as the **max** present on the CSV file. Anybody can help?

**Comment by jbax** [comment]
Format applies to numbers or dates. It won't work if `myField` is of type `String`.

This should work:

```
	public static class Test {
		@Format(formats = "0000")
		@Parsed
		Integer number;
	}
```

What you can do is to create your custom conversion class to handle your case. 

```
@Convert(conversionClass=MyFormatter.class, args="8")     
@Parsed(field = "myfield")  
String myfield;
```

**Comment by tonycatapano** [comment]
Thanks for the answer, does this mean that the only way to format a String field in **input** is to create a custom conversion class?

**Comment by jbax** [comment]
Yes

On 26 Jan. 2018 8:30 pm, "Tonino Catapano" <notifications@github.com> wrote:

Thanks for the answer, does this mean that the only way to format a String
field in *input* is to create a custom conversion class?

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/uniVocity/univocity-parsers/issues/220#issuecomment-360736408>,
or mute the thread
