### ISSUE TITLE
Export/Import of nested lists

### ISSUE THREAD

**Issue by tanyona** [uniVocity/univocity-parsers#222]
This is more asking for a recommendation or guidance. For class structures as follows

```
public class User {
	
	@Parsed
	private String name;
	@Nested
	private List<Country> countries;
	
	//getters and setters...
}

public class Country {
	
	@Parsed
	private String name;
	
	//getters and setters...
}
```

How would one go about exporting a list of `User` objects to csv, and later importing the csv output to a List of User objects.

**Comment by jbax** [comment]
It looks like you are approaching this the wrong way. What is the input format to read/write? 

This sort of class structure you just created is not the easiest or cleanest to work with. It can work if you have multiple columns for `Country`. For example. if your input contains columns such as `username`, `country1`, `country2`, `country3`, etc then it can work. If that's the case, there's a similar example for this here:

https://github.com/uniVocity/univocity-parsers/blob/master/src/test/java/com/univocity/parsers/issues/github/Github_159.java#L216

Otherwise your best bet is to write your users in a file, countries in another, and use some sort of ID column to "join" the values manually.

Not sure if it helps.

**Comment by tanyona** [comment]
OK. I can look at the separate files route. There is no defined input/output format. I would be the one to decide that, which is why I was asking for advice. I was also thinking about a master-detail type format where a user row is followed by country rows. What would your thoughts be on such a layout.
