### ISSUE TITLE
Reusing CsvRoutines object results in unexpected output

### ISSUE THREAD

**Issue by tanyona** [uniVocity/univocity-parsers#224]
I have code like the following

```
CsvWriterSettings writerSettings = new CsvWriterSettings();
writerSettings.setHeaderWritingEnabled(true);
CsvRoutines csvRoutines = new CsvRoutines(writerSettings);

csvRoutines.writeAll(users, User.class, usersFile);
csvRoutines.writeAll(countries, Country.class, countriesFile);
```

The output in the `countriesFile` seems to have headers from the User class. If I create a new `CsvRoutines` object and use that for the second `writeAll`, the output is fine. Is it by design that one is not supposed to reuse a CsvRoutines object.

**Comment by jbax** [comment]
Thanks for reporting this one. I just fixed it and released a 2.6.0-SNAPSHOT build with it.

Basically it happened because the headers are derived from the class **IF** no headers have been defined manually. When you reuse a routines instance with a different class the headers are already there so it wouldn't derive them again.

I just made an adjustment to make this work as it should.
Thank you for using our parsers!
