### ISSUE TITLE
CSV - asure delimiter not in content

### ISSUE THREAD

**Issue by blackfoxoh** [uniVocity/univocity-parsers#232]
I have a usecase I'm not sure how to handle this the best way. I have to export a csv with ";" as the delimiter. The receiver of the file explicitly states that this character must not occur in the content (because it is the delimiter). Sadly they don't offer to use any quote-character.
Hence I need to remove or replace the delimiter-character in all content-Strings.
One solution may be to use a conversion to achieve this but I'm wondering if there maybe is a setting in univocity-parsers to handle this? The solution with the conversion has the drawback of handling non-charsequence values like Integer objects etc. or applying the conversion only to some char-fields but then a future new column might be forgotten to convert as well...
Such a feature (if present or newly implemented) maybe solves the usecase of issue #215 as well...?

Is this feature already available somehow? If not regard this as a feature request :-)

**Comment by jbax** [comment]
The custom conversion is the way to go. I'm working on updating the tutorials and used your situation to implement a "clean" solution that uses from meta-annotations. You should probably use this as well.

Here is my implementation of a custom conversion: [ContentCleaner.java](https://github.com/uniVocity/univocity-parsers/blob/master/src/test/java/com/univocity/parsers/annotations/meta/ContentCleaner.java)

Here is the meta-annotation: [Clean](
https://github.com/uniVocity/univocity-parsers/blob/master/src/test/java/com/univocity/parsers/annotations/meta/Clean.java). The `@Parsed` and `@Convert` annotations are applied to the `@Clean` annotation itself - there the characters to remove from values written/parsed are 'a' and ';'.

Now all you have to do is to annotated your classes with `@Clean`, as I did in [CleanBeanTest](https://github.com/uniVocity/univocity-parsers/blob/master/src/test/java/com/univocity/parsers/annotations/meta/CleanBeanTest.java)

There's a test case [here](https://github.com/uniVocity/univocity-parsers/blob/master/src/test/java/com/univocity/parsers/annotations/AnnotationHelperTest.java#L42)

Note that I just fixed a bug that was causing issues deriving the headers to write from the class being written. I suggest you to update to version 2.6.2, otherwise you might have to set the headers manually in the writer settings.

Hope this helps!
Thank you for using our parsers

**Comment by blackfoxoh** [comment]
Thank you for the hint.
I have implemented my own conversion now. Using Anotations isn't a solution for me as I don't use Beans for writing in this case.
