### ISSUE TITLE
CsvParser method setNumberOfRowsToSkip does not work with selectFields parser setting

### ISSUE THREAD

**Issue by samliu2000** [uniVocity/univocity-parsers#261]
Dear Univocity-parser, awesome parser this is!
Found this issue and want to share with you, in this case, tempData will be getting the right size, which is the dataset after the line skipped, but with all empty value. Please investigate and see whether this is because the lines skipped actually includes the header line that is actually the first line in the csv data file. If it is, can we read the first line to determine the parsing needed info then skip the needed lines?

CsvParserSettings csvparser_setting = new CsvParserSettings();
csvparser_setting.selectFields("Time", "City", "State", "Value");
csvparser_setting.getFormat().setLineSeparator("\n");
csvparser_setting.setNumberOfRowsToSkip(10); //doesn't work
CsvParser  parser = new CsvParser (csvparser_setting);
tempData = parser.parseAll(new File("C:\\temp\\data.csv"));

Thanks!

**Comment by jbax** [comment]
How does your input file look like? 

I believe your issue comes from calling `selectFields` without you defining the headers. The parser will extract the headers from the first line it processes IF you configure it to do so with `csvparser_setting.setHeaderExtractionEnabled(true);` but that will happen AFTER the 10 lines are skipped. 

If your headers are declared in the first row of your CSV and you want to skip 10 rows AFTER the headers, then you probably need to do the following:

                CsvParserSettings csvparser_setting = new CsvParserSettings();
		csvparser_setting.selectFields("Time", "City", "State", "Value");
		
		// configure the parser to extract headers
		csvparser_setting.setHeaderExtractionEnabled(true);

		CsvParser parser = new CsvParser (csvparser_setting);
		
		//prepare the parser to run.
		parser.beginParsing(new File("C:\\temp\\data.csv"));

		// make the parser collect headers from the first row.
		parser.getContext().headers();

		//skip 10 lines.
		parser.getContext().skipLines(10); 

		//now, parse everything. 
		List<String[]> tempData = parser.parseAll();

**Comment by samliu2000** [comment]
Very cool, I am sorry that I didn't know I could do this before. Thank you very much for explaining this. -Sam


________________________________
