### ISSUE TITLE
'\u0000' characters with custom quote escaping.

### ISSUE THREAD

**Issue by twiechert** [uniVocity/univocity-parsers#304]
(1) Having changed the code quote escaping to:

```
    parserSettings.getFormat().setQuoteEscape('\\');
    parserSettings.getFormat().setCharToEscapeQuoteEscaping('\\');
```

(2) Then reading an UTF-16 csv file from a random byte position in the middle of the file plus a call of
```
 parser.parseNext();
```
To make sure to get a proper line.

(3) I receive records where every character is preceded by '\u0000', so that ``hello`` becomes ``\u0000h\u0000e\u0000l\u0000l\u0000o``.

I'm using univocity 2.7.6. Reading the file regularly from the beginning does not cause these issues.

**Comment by twiechert** [comment]
Hey thanks for the fast response.
I extracted the relevant parts into a demo repo.

Please find the test case here

https://github.com/twiechert/univocity-parsers-demo-bug/blob/master/src/test/java/CsvConnectorTest.java

assertTrue(!record.contains("\u0000"));

should not trigger but does.

**Comment by jbax** [comment]
The problem here is that you are not providing the encoding of the inputstream explicitly.

Try `csvParser.beginParsing(fis, "UTF-16");` instead of `csvParser.beginParsing(fis);`.

The parser will detect the encoding automatically based on the first few bytes of your input. As you are skipping these bytes there is no way to detect the proper encoding and the parser will simply use the platform's default.

I also suggest you to check what character is at the position before you run the parsing process. If by bad luck you end on a `"` it may run like crazy trying to find the closing quote. That could swallow a large bunch of records.

Hope this helps and thank you for using our parsers!

**Comment by jbax** [comment]
> Does this also hold when every record is enclosed by "record" and does the amount of records skipped in the worst case have an upper bound?

Assume you have `"record 1"\n"record 2"\n"record 3"\n` and you end up on the quote preceding the `\n`. In that case the parser will start accumulating the value after the quote as `\n"record 2"\n"record 3"\n` and so on.

It will be safer to skip one character so it then starts from the `\n` character. Alternatively you can also set `unescapedQuoteHandling=SKIP_VALUE` so whatever is found and detected as a value with unescaped quotes will be discarded.
