### ISSUE TITLE
Why doesn't CsvWriter throw checked exception? 

### ISSUE THREAD

**Issue by bhazelwood** [uniVocity/univocity-parsers#312]
As per the title is there some reason why the CsvWriter does not throw checked exceptions? For example, passing a file with non-writable permissions? 

Is there a standard way of catching these exceptions? Hard to know which ones to catch when they aren't declared.

**Comment by jbax** [comment]
It doesn't throw checked exceptions because that would make it a very annoying API to work with. If you give it a unwritable file, you'll get an `IllegalArgumentException` (which makes sense, as the file is an argument, and it is invalid).

 You can always get the exception cause from whatever the parser throws at you to get the original exception.
