### ISSUE TITLE
CSVParser Out of Memory Error

### ISSUE THREAD

**Issue by thesuhtz** [uniVocity/univocity-parsers#361]
Hello,

Im trying to parse a very huge CSV file (around 800+ MB) and it's always giving me a

Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.util.HashMap.resize(HashMap.java:559)
	at java.util.HashMap.addEntry(HashMap.java:851)
	at java.util.LinkedHashMap.addEntry(LinkedHashMap.java:427)
	at java.util.HashMap.put(HashMap.java:484)
	at com.univocity.parsers.common.record.RecordImpl.fillFieldObjectMap(RecordImpl.java:435)
	at com.util.FileUtil.readCSVFileUsingUni(FileUtil.java:206)
	at com.import.process(Import.java:117)
	at com.main(Import.java:42)

Below is the code snippet:

try {
   parser.beginParsing(new BufferedReader(new FileReader(filename)));      
   Record record = null;

   while ((record = parser.parseNextRecord()) != null) {
      LinkedHashMap<String, Object> values = new LinkedHashMap<>();
      record.fillFieldObjectMap(values);
      importFileRowMapList.add(values);
   }
} catch (FileNotFoundException ex) {
   Logger.getLogger(FileUtil.class.getName()).log(Level.SEVERE, null, ex);
}

Any idea on a fix/workaround? This project was just turned over to me and Im still trying to familiarize myself with Univocity.

Thank you in advance!

**Comment by jbax** [comment]
The issue here is in the code that is adding everything into a list (`importFileRowMapList`) - keeping what the parser returns in memory is not a good idea when the input is large. If you can, try to use the result written to your `values` map immediately instead of adding everything to a list that will later be used for something else.

If you can't or it is too hard your only option is to increase the amount of memory allocated to the JVM using the `Xms` and `Xmx` flags (https://stackoverflow.com/questions/14763079/what-are-the-xms-and-xmx-parameters-when-starting-jvm).

Hope this helps.
Thank you for using our parsers!
