### ISSUE TITLE
CSV reader for BOM file produces unwanted unicode replacement char

### ISSUE THREAD

**Issue by MrRexZ** [uniVocity/univocity-parsers#364]
I'm on version `2.8.3` of the library.
Given a UTF-8 encoded (with BOM) CSV file with the content after inspecting with VIM in binary format :
```
<feff>col1^M
foo^M
```
With `CsvParser`, I first parse with the bytes I read from a file (by `parser.beginParsing(bytes)`) and then using  `parser.getContext.headers()` to extract the headers (without hard-coding the headers via setting), and I'm getting unicode replacement chars in place of the BOM chars.

The result header text is of following `��col1` (should be `col1`). It seems that the BOM is not escaped properly. 
I also notice that <feff> is a BOM for UTF-16 file, but the rest of the chars are encoded in UTF-8. Could this be because the library didn't have handler/check for this scenario?

**Comment by jbax** [comment]
Now that's an interesting one. I could not reproduce if the entire file is encoded with UTF-8. In that case the `FEFF` is skipped normally and the file is read.

```
	byte[] b1 = "\uFEFF".getBytes("UTF-8");
		byte[] b2 = "col1\nfoo".getBytes("UTF-8");

		byte[] b = new byte[b1.length + b2.length];
		System.arraycopy(b1, 0, b, 0, b1.length);
		System.arraycopy(b2, 0, b, b1.length, b2.length);

		CsvParserSettings parserSettings = new CsvParserSettings();
		parserSettings.setHeaderExtractionEnabled(true);
		parserSettings.getFormat().setLineSeparator("\n");
		CsvParser parser = new CsvParser(parserSettings);
		parser.beginParsing(new ByteArrayInputStream(b));
		System.out.println(Arrays.toString(parser.getContext().headers()));
```

Prints out: `[col1]`

The only way to make this output the incorrect values is to change the first line to mix up the encodings:

```
	byte[] b1 = "\uFEFF".getBytes("UTF-16");
	byte[] b2 = "col1\nfoo".getBytes("UTF-8");
        ....
```

Now with two different encodings it will print out: `[捯氱੦潯]`

Which is expected because the characters after `FEFF` will be read using UTF 16 and they are not encoded using that.

So you need to explicitly provide the encoding when parsing:

```
parser.beginParsing(new ByteArrayInputStream(b), "UTF-8");
```

Which gives me: `[����col1]`

The only solution for that is to skip the first few bytes:

```
ByteArrayInputStream in = new ByteArrayInputStream(b);
in.skip(4);
parser.beginParsing(in, "UTF-8");
```

Now you will get `[col1]`.

There is no way to handle this in a sane or general way from within the parser. You need to fix the file yourself or read the first few bytes in the input stream to find out if they are a BOM marker, and if they are not, reopen the input stream.

Hope this helps.
