### ISSUE TITLE
columnReorderingEnabled and selectFields

### ISSUE THREAD

**Issue by GreenFur05** [uniVocity/univocity-parsers#370]
Hey @jbax, I'm preparing to submit a PR to enable columnReordering for beans, which is all looking good, except I'm running into a few issues regarding fillOutputRow(). Specifically, the test Ticket_14 has got me stumped.

I understand the capability that you outlined when you created the test in your commit message, when the selection is greater than the actual columns available, although the test values you're providing align with the selection, not the actual headers. Shouldn't this be the other way around? Where the headers dictate the data to be written, and the selection manipulating the output of the data?

Let me know if I've got this wrong, and I'll work around accordingly.

Cheers

**Comment by jbax** [comment]
Hi Lachlan, thank you for your help.

On Ticket_14, the values align with the selection because that's the format
of the data received from somewhere. The headers define where these values
should end up.

If you get stuck with your PR don't give up. Just submit it with some unit
tests for what you intend to implement/fix and I'll try to make the
necessary adjustments.

Again, thank you for your contribution.
Happy holidays
Jeronimo

**Comment by jbax** [comment]
Closing this for now. Feel free to reopen in case you have issues. Thanks!
