### ISSUE TITLE
make the maxRowSample parameter public configurable

### ISSUE THREAD

**Issue by nihaoo** [uniVocity/univocity-parsers#408]
Look like the maxRowSample parameter is hardcoded to 20 in the com.univocity.parsers.csv.CsvParser.java:
(https://github.com/uniVocity/univocity-parsers/blob/3c2c2fa22ef6f53f8a94bedc9b398daaf45fe23f/src/main/java/com/univocity/parsers/csv/CsvParser.java#L466)
----------------------------------------------------------------------------------
	protected final InputAnalysisProcess getInputAnalysisProcess() {
		if (settings.isDelimiterDetectionEnabled() || settings.isQuoteDetectionEnabled()) {
			return new CsvFormatDetector(20, settings, whitespaceRangeStart) {
				@Override
				void apply(char delimiter, char quote, char quoteEscape) {
					if (settings.isDelimiterDetectionEnabled()) {
						CsvParser.this.delimiter = delimiter;
						CsvParser.this.delimiters[0] = delimiter;
-------------------------------------------------------------------------------------

Could we make maxRowSample a public configurable parameter? we would like to increase the value of maxRowLines to increase the delimiter detection accuracy.

**Comment by tiddman** [comment]
@jbax This issue is unfortunately a deal breaker for us because we have found errors in the delimiter detection in production using only 20 lines, whereas increasing this to i.e. 100 works.  Because of where this is hard coded our only option is to fork the code and build our own jar which we'd really rather avoid if possible.  Can you give any indication about timeline or priority for this change? Thanks so much.

**Comment by jbax** [comment]
Done, I'll release a new version later today. Thank you for using our parsers!

**Comment by tiddman** [comment]
@jbax Outstanding! Thank you!
