### ISSUE TITLE
[CsvParser] Trailing space after quoted content is always ignored

### ISSUE THREAD

**Issue by juliette-derancourt** [uniVocity/univocity-parsers#439]
Hello,

I just stumbled upon a small bug (I guess?) with the `CsvParser` :)

In the following test, I set `ignoreLeadingWhitespaces` and `ignoreTrailingWhitespaces` to false.

```java
@Test
void parseCsvLine() {
	CsvParserSettings settings = new CsvParserSettings();
	settings.getFormat().setQuote('\'');
	settings.setEmptyValue("");
	settings.setIgnoreLeadingWhitespaces(false);
	settings.setIgnoreTrailingWhitespaces(false);
	CsvParser csvParser = new CsvParser(settings);

	assertThat(csvParser.parseLine("1, 'a' ")).isEqualTo(new String[]{ "1", " 'a' " }); // OK
	assertThat(csvParser.parseLine("2, 'a'")).isEqualTo(new String[]{ "2", " 'a'" }); // OK
	assertThat(csvParser.parseLine("3,'a' ")).isEqualTo(new String[]{ "3", "'a' " }); // FAIL
}
```

The two first cases are parsed as expected. However, the third one is parsed as `["3", "a"]` instead of `["3", "'a' "]`.
Is this an expected behavior?

Thanks! :smile:

**Comment by jbax** [comment]
Actually the parser is working as expected in this scenario. The quote handling does not kick in in your first 2 tests because the first character is a whitespace you choose not to ignore. There parser will NOT handle this as a quoted field and that's why the output is ` 'a' ` instead of ` a ` (notice that quotes were not removed).

In the last test, the quote is the very first character, which means this is a quoted field and the output will be the content within the quotes, so you will get `a` (quotes are gone). That whitespace after the quote is filtered out as just noise and not included in the value extracted out of the quoted part.

Hope this makes sense.
Thank you for using our parsers!

**Comment by juliette-derancourt** [comment]
@jbax Thanks for the answer! :)
