### ISSUE TITLE
Process Bean iteratively

### ISSUE THREAD

**Issue by maksimu** [uniVocity/univocity-parsers#44]
How can I process CSV file as big as 5GB (I'm processing NPI data http://download.cms.gov/nppes/NPI_Files.html) with BeanProcessor. You have an example that loads all data into a memory. Is it possible to process it iteratively without loading the whole file into a memory first?

**Comment by jbax** [comment]
Use the (BeanProcessor)[https://github.com/uniVocity/univocity-parsers/blob/master/src/main/java/com/univocity/parsers/common/processor/BeanProcessor.java] instead of BeanListProcessor and you're good.

**Comment by helt** [comment]
Is there an example for using the BeanProcessor working iteratively? Or a hint which way to go in order to get a `Iteraterable<MyBean>` which parses the csv iteratively? I think, its not advisable to add `parser.parseLine()` login in the processor itself, right?

PS: Sorry for hijacking the issue.

**Comment by jbax** [comment]
Not sure what you need. You'll receive the beans one by one from the callback method `beanProcessed` in `BeanProcessor`. Just call `parser.parse(your input here)`.

If you use `parser.parseLine()`, with a row processor, the row processor will be executed as well. In this case, if you are using a `BeanProcessor`, every time `parseLine()` is called then a new bean instance will pop up in the `beanProcessed` callback.

**Comment by helt** [comment]
if i interprete the data flow correctly, this will result in the parser parsing my 28gb file as fast as possible. However, a huge queue will build up, because consuming the processed beans will take WAY longer than parsing them. 

As such, the vm will run out of memory sooner or later... 

Is it feasible to change the BeanProcessor Contract, so that beanProcessed will change from `public void beanProcessed()` to `public T beanProcessed()`, for immediate consumption instead of handing it over in the method body?

**Comment by jbax** [comment]
It doesn't enqueue the rows so that's not a problem at all. You can simply use the beanProcessed method and not worry about it. A new bean will only be created once your bean consumption process is done.

If you want you can also enqueue the beans in a blocking queue and keep polling from it in a separate thread, but it may be slower than to just consume the beans with no threading at all.

**Comment by jbax** [comment]
In the process of preparing the release of version 2.0.0, and reviewing past issues, I found your question.
I think you could also use the new routines API as demonstrated in this example [this commit](https://github.com/uniVocity/univocity-parsers/commit/4b74fdfe56b656e04923eb20cb2d19c26fa00b78#diff-35f8b5a405354ccf5a9c201ec69d91feR46)
