### ISSUE TITLE
problem with a csv-file

### ISSUE THREAD

**Issue by larsniemann1983** [uniVocity/univocity-parsers#61]
Hi,

we've got a problem wit the followin csv-file (example extracted):

example;"this is a "super example"";example3

This works:

example;"this is a "super example" ";example3

But if the cell with the quoted value ends with "", the parsing fails.

What is your suggestion?

**Comment by jbax** [comment]
Set the quote escape to something like '\0' if you know no values will be escaped. I had to make and adjustment on the parser handle the case you reported as well. I released another 2.0.0-SNAPSHOT build to include this update.

If you can have quotes escaped as well as not escaped, then the problem is not deterministic and there's no way to parse this reliably.

Hope this helps.
Thank you for using our parsers!
