### ISSUE TITLE
disable max characters per column

### ISSUE THREAD

**Issue by rhl-** [uniVocity/univocity-parsers#96]
Is there any way to disable: setMaxCharsPerColumn

We don't know how many characters will appear per column, without estimating the number of characters based on the number of bytes in the file.

**Comment by jbax** [comment]
Currently not but it's planned to be introduced in version 2.2.0.

You can set `maxCharsPerColumn` to `Integer.MAX_VALUE`. Remember that no `String` in java can be longer than `Integer.MAX_VALUE`, because Strings store an array characters internally, and arrays are indexed by `int`. If you try to go over that limit you'll receive an `OutOfMemoryError` (i.e. an instance of `Error` instead of `Exception`) and are likely to crash your application because the error won't stop at try/catch(Exception ex) blocks - only try/catch(Throwable ex) will catch that.

**Comment by jbax** [comment]
Done, just set  `maxCharsPerColumn = -1` and it will work.

I've released version 2.2.0-SNAPSHOT with this enhancement.

Thank you for using our parsers!
