### ISSUE TITLE
Setting, that disables csv content in error messages

### ISSUE THREAD

**Issue by mdanetzky** [uniVocity/univocity-parsers#98]
We parse sensitive data which cannot get stored in the logs. 
Is there a way to disable it from appearing in the exception messages?

**Comment by jbax** [comment]
Currently not. I will add a configuration option for this in the next version as you're not the first user who complains about that :)

**Comment by jbax** [comment]
Done. Grab the latest version 2.2.0-SNAPSHOT and you'll find the `setErrorContentLength(int);` in any of the configuration classes for both parsing and writing.

You can now restrict the length of the content printed in these error messages. In addition, you can remove the information altogether by setting the length to 0 (check the javadocs). In this case, the exception objects themselves won't have information about the data being parsed/written.

**Comment by wregab** [comment]
Hi jbax, thanks for the feature.

Although I think that we should make an assumption that data is by default sensitive (default error content length set to zero), and if a user wants to debug, she would turn verbosity on.

This approach is widely used (ie. logs in Hibernate).
What do You think about applying it here?

**Comment by jbax** [comment]
@wregab I don't agree with this one. In most cases users want to have error messages as descriptive as possible to help them find the cause of the error. I believe hibernate disables verbosity by default for performance reasons as every query gets logged, instead of data security. 

This is not the case of the parser where everything stops in case a problematic input is parsed. If you are concerned about data security (not the majority of users), the option of disabling data in exceptions and error messages is there.

**Comment by jbax** [comment]
FYI: improvements implemented in [this commit](https://github.com/uniVocity/univocity-parsers/commit/321ee3a9b4aa69e53ed64df0efb93d627429f44d) so all occurences of `DataProcessingException` produce the expected output.
